"""added zero index genus and family to AppTaxa

Revision ID: 0df16c848589
Revises: c4ffc47284e3
Create Date: 2026-06-19 10:18:28.980769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0df16c848589"
down_revision: Union[str, Sequence[str], None] = "c4ffc47284e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_taxa", sa.Column("zero_indexed_genus", sa.Integer(), nullable=True)
    )
    op.add_column(
        "app_taxa", sa.Column("zero_indexed_family", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_taxa", "zero_indexed_family")
    op.drop_column("app_taxa", "zero_indexed_genus")
    # ### end Alembic commands ###
