"""updated foreign key relationship between classification and filtered inat observations

Revision ID: 528c8d11d272
Revises: c2534e585edf
Create Date: 2026-06-04 15:53:52.171031

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "528c8d11d272"
down_revision: Union[str, Sequence[str], None] = "c2534e585edf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
