"""changed train to bool in inatclassdataset

Revision ID: 5bba576fbbfa
Revises: e9217b237685
Create Date: 2026-05-24 17:10:43.936501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bba576fbbfa'
down_revision: Union[str, Sequence[str], None] = 'e9217b237685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inat_classification_dataset', 'train',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
                postgresql_using ='train::boolean',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inat_classification_dataset', 'train',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
