"""location, common name, depth added to AppTaxa

Revision ID: 62a985cf0847
Revises: d7ae70c442b9
Create Date: 2026-06-16 16:09:29.568963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62a985cf0847"
down_revision: Union[str, Sequence[str], None] = "d7ae70c442b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_taxa", sa.Column("common_name", sa.String(), nullable=True))
    op.add_column(
        "app_taxa", sa.Column("location", sa.ARRAY(sa.String()), nullable=False)
    )
    op.add_column("app_taxa", sa.Column("depth", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_taxa", "depth")
    op.drop_column("app_taxa", "location")
    op.drop_column("app_taxa", "common_name")
    # ### end Alembic commands ###
