"""corrected subfamily -> family

Revision ID: 6ff1a7878aff
Revises: f1a2b3c4d5e6
Create Date: 2026-06-15 19:45:13.598871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ff1a7878aff"
down_revision: Union[str, Sequence[str], None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inat_classification_dataset", sa.Column("family", sa.Integer(), nullable=True)
    )
    op.add_column(
        "inat_classification_dataset",
        sa.Column("zero_indexed_family", sa.Integer(), nullable=True),
    )
    op.drop_column("inat_classification_dataset", "zero_indexed_subfamily")
    op.drop_column("inat_classification_dataset", "subfamily")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inat_classification_dataset",
        sa.Column("subfamily", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "inat_classification_dataset",
        sa.Column(
            "zero_indexed_subfamily", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("inat_classification_dataset", "zero_indexed_family")
    op.drop_column("inat_classification_dataset", "family")
    # ### end Alembic commands ###
