"""annotations added to inat

Revision ID: 7292239f728e
Revises: 5bba576fbbfa
Create Date: 2026-05-24 17:22:11.630780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7292239f728e"
down_revision: Union[str, Sequence[str], None] = "5bba576fbbfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inat_classification_dataset",
        sa.Column("annotation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inat_classification_dataset", "annotation")
    # ### end Alembic commands ###
