"""Clip context table

Revision ID: a31bb45a794f
Revises: 998a3198ce78
Create Date: 2026-05-07 20:46:11.114731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a31bb45a794f"
down_revision: Union[str, Sequence[str], None] = "998a3198ce78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inat_clip_context",
        sa.Column("photo_uuid", sa.String(length=36), nullable=False),
        sa.Column("is_underwater", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["photo_uuid"],
            ["inat_filtered_observations.photo_uuid"],
            name=op.f("fk_inat_clip_context_photo_uuid_inat_filtered_observations"),
        ),
        sa.PrimaryKeyConstraint("photo_uuid", name=op.f("pk_inat_clip_context")),
    )
    op.create_index(
        "ix_inat_clip_context_is_underwater",
        "inat_clip_context",
        ["is_underwater"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inat_clip_context_is_underwater", table_name="inat_clip_context")
    op.drop_table("inat_clip_context")
    # ### end Alembic commands ###
