"""widen dive_regions.iso_country (Natural Earth ISO_A2 has variants like CN-TW)

Revision ID: a7b8c9d0e1f2
Revises: 6f36d67ce30c
Create Date: 2026-07-16 12:00:00.000000

d4e5f6a7b8c9 created iso_country as varchar(2) assuming strict ISO 3166-1
alpha-2, but Natural Earth's ISO_A2 field carries non-alpha-2 variants
('CN-TW' for Taiwan, '-99' for unknowns), which overflow varchar(2) during the
region seed. The earlier fix attempt (6f36d67ce30c) autogenerated empty and is
already applied to prod, so this revision carries the actual ALTER. Drop the
length cap; seed_regions and derive_species_regions read the same raw ISO_A2,
so the join stays consistent at any width.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7b8c9d0e1f2"
down_revision: Union[str, Sequence[str], None] = "6f36d67ce30c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        "dive_regions",
        "iso_country",
        existing_type=sa.String(length=2),
        type_=sa.String(),
        existing_nullable=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Narrowing back to varchar(2) truncates any longer values (e.g. 'CN-TW').
    # USING left-truncates so the ALTER doesn't error if such rows exist.
    op.alter_column(
        "dive_regions",
        "iso_country",
        existing_type=sa.String(),
        type_=sa.String(length=2),
        existing_nullable=True,
        postgresql_using="left(iso_country, 2)",
    )
