"""observation effective label + label_status

Revision ID: b09382574363
Revises: b1a2cea8dd23
Create Date: 2026-06-23 12:39:10.313464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09382574363'
down_revision: Union[str, Sequence[str], None] = 'b1a2cea8dd23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('label_status', sa.String(length=20), server_default='predicted', nullable=False))
    op.alter_column('observations', 'corrected_taxon_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observations', 'corrected_taxon_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('observations', 'label_status')
    # ### end Alembic commands ###
