"""add user observation tracking tables

Revision ID: b1a2cea8dd23
Revises: 0df16c848589
Create Date: 2026-06-23 10:15:09.657060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1a2cea8dd23"
down_revision: Union[str, Sequence[str], None] = "0df16c848589"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("google_subject_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "google_subject_id", name=op.f("uq_users_google_subject_id")
        ),
    )
    op.create_table(
        "dive_sites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_key", sa.String(length=255), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_dive_sites_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dive_sites")),
        sa.UniqueConstraint("name_key", name=op.f("uq_dive_sites_name_key")),
    )
    op.create_table(
        "dives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column("gps_lat", sa.Float(), nullable=True),
        sa.Column("gps_lng", sa.Float(), nullable=True),
        sa.Column("dived_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["dive_sites.id"],
            name=op.f("fk_dives_site_id_dive_sites"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_dives_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dives")),
    )
    op.create_index(
        "ix_dives_user_id_dived_at", "dives", ["user_id", "dived_at"], unique=False
    )
    op.create_table(
        "observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dive_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("predicted_taxon_id", sa.BigInteger(), nullable=True),
        sa.Column("corrected_taxon_id", sa.BigInteger(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("depth_m", sa.Float(), nullable=True),
        sa.Column("observed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["corrected_taxon_id"],
            ["inat_taxa.taxon_id"],
            name=op.f("fk_observations_corrected_taxon_id_inat_taxa"),
        ),
        sa.ForeignKeyConstraint(
            ["dive_id"],
            ["dives.id"],
            name=op.f("fk_observations_dive_id_dives"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["predicted_taxon_id"],
            ["inat_taxa.taxon_id"],
            name=op.f("fk_observations_predicted_taxon_id_inat_taxa"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_observations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
    )
    op.create_index(
        "ix_observations_user_id", "observations", ["user_id"], unique=False
    )
    op.create_table(
        "observation_photos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("image_path", sa.String(length=512), nullable=False),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("predicted_taxon_id", sa.BigInteger(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_observation_photos_observation_id_observations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["predicted_taxon_id"],
            ["inat_taxa.taxon_id"],
            name=op.f("fk_observation_photos_predicted_taxon_id_inat_taxa"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation_photos")),
    )
    op.create_index(
        "ix_observation_photos_observation_id",
        "observation_photos",
        ["observation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_observation_photos_observation_id", table_name="observation_photos"
    )
    op.drop_table("observation_photos")
    op.drop_index("ix_observations_user_id", table_name="observations")
    op.drop_table("observations")
    op.drop_index("ix_dives_user_id_dived_at", table_name="dives")
    op.drop_table("dives")
    op.drop_table("dive_sites")
    op.drop_table("users")
    # ### end Alembic commands ###
