"""added zero indexed classes

Revision ID: c2534e585edf
Revises: b4f7e2a9c3d1
Create Date: 2026-05-30 19:21:37.456500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2534e585edf'
down_revision: Union[str, Sequence[str], None] = 'b4f7e2a9c3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inat_classification_dataset', sa.Column('zero_indexed_subfamily', sa.Integer(), nullable=True))
    op.add_column('inat_classification_dataset', sa.Column('zero_indexed_genus', sa.Integer(), nullable=True))
    op.add_column('inat_classification_dataset', sa.Column('zero_indexed_species', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inat_classification_dataset', 'zero_indexed_species')
    op.drop_column('inat_classification_dataset', 'zero_indexed_genus')
    op.drop_column('inat_classification_dataset', 'zero_indexed_subfamily')
    # ### end Alembic commands ###
