"""nullable cols

Revision ID: c4ffc47284e3
Revises: 62a985cf0847
Create Date: 2026-06-16 17:18:02.675716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4ffc47284e3"
down_revision: Union[str, Sequence[str], None] = "62a985cf0847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_taxa", sa.Column("img_count", sa.Integer(), nullable=True))
    op.alter_column(
        "app_taxa",
        "location",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.alter_column("app_taxa", "depth", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("app_taxa", "depth", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "app_taxa",
        "location",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    op.drop_column("app_taxa", "img_count")
    # ### end Alembic commands ###
