"""locations (dive_regions, species_regions) and extended dive log

Revision ID: d4e5f6a7b8c9
Revises: b7d2e1a94c30
Create Date: 2026-07-16 00:00:00.000000

Phase 1 foundation: make location a first-class entity (geographic/political
region hierarchy + species↔region many-to-many) and extend the dive log to a
full dive-computer-style record. Hand-written (not autogenerated) so the
`verified` server_default and the FK ondelete clauses are explicit.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "d4e5f6a7b8c9"
down_revision: Union[str, Sequence[str], None] = "b7d2e1a94c30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Extended dive-log columns (all nullable, metric-canonical). `verified` is
# handled separately below (NOT NULL + server_default).
_DIVE_COLUMNS = (
    ("visibility_m", sa.Float()),
    ("air_temp_c", sa.Float()),
    ("water_temp_c", sa.Float()),
    ("weight_kg", sa.Float()),
    ("exposure_suit", sa.String(length=100)),
    ("depth_avg_m", sa.Float()),
    ("depth_max_m", sa.Float()),
    ("started_at", sa.DateTime()),
    ("bottom_time_min", sa.Integer()),
    ("total_time_min", sa.Integer()),
    ("end_pressure_bar", sa.Float()),
    ("dive_shop", sa.String(length=255)),
    ("verified_source", sa.String(length=50)),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ── dive_regions: self-referential geographic hierarchy ──────────────────
    op.create_table(
        "dive_regions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_key", sa.String(length=255), nullable=False),
        sa.Column("iso_country", sa.String(length=2), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["dive_regions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_id", "name_key", name="uq_dive_regions_parent_name"
        ),
    )
    op.create_index("ix_dive_regions_kind", "dive_regions", ["kind"])
    op.create_index("ix_dive_regions_iso_country", "dive_regions", ["iso_country"])

    # ── species_regions: species ↔ region many-to-many ───────────────────────
    op.create_table(
        "species_regions",
        sa.Column("taxon_id", sa.BigInteger(), nullable=False),
        sa.Column("region_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("obs_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["taxon_id"], ["inat_taxa.taxon_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["dive_regions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("taxon_id", "region_id"),
    )
    # Reverse lookup (species-in-region); the composite PK already covers taxon.
    op.create_index(
        "ix_species_regions_region_id", "species_regions", ["region_id"]
    )

    # ── dive_sites: link to region + Google Places id ────────────────────────
    op.add_column(
        "dive_sites",
        sa.Column("region_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.add_column(
        "dive_sites",
        sa.Column("google_place_id", sa.String(length=255), nullable=True),
    )
    op.create_foreign_key(
        "fk_dive_sites_region_id",
        "dive_sites",
        "dive_regions",
        ["region_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # ── dives: extended dive-log fields ──────────────────────────────────────
    for name, coltype in _DIVE_COLUMNS:
        op.add_column("dives", sa.Column(name, coltype, nullable=True))
    # NOT NULL + server_default → existing rows backfill to false via a single
    # fast catalog update (constant default, no per-row rewrite on PG 11+).
    op.add_column(
        "dives",
        sa.Column(
            "verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("dives", "verified")
    for name, _ in reversed(_DIVE_COLUMNS):
        op.drop_column("dives", name)

    op.drop_constraint("fk_dive_sites_region_id", "dive_sites", type_="foreignkey")
    op.drop_column("dive_sites", "google_place_id")
    op.drop_column("dive_sites", "region_id")

    op.drop_index("ix_species_regions_region_id", table_name="species_regions")
    op.drop_table("species_regions")

    op.drop_index("ix_dive_regions_iso_country", table_name="dive_regions")
    op.drop_index("ix_dive_regions_kind", table_name="dive_regions")
    op.drop_table("dive_regions")
