"""added app taxa

Revision ID: d7ae70c442b9
Revises: 6ff1a7878aff
Create Date: 2026-06-16 13:36:00.270307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7ae70c442b9"
down_revision: Union[str, Sequence[str], None] = "6ff1a7878aff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_taxa",
        sa.Column("taxon_id", sa.Integer(), nullable=False),
        sa.Column("zero_indexed_species", sa.Integer(), nullable=True),
        sa.Column("species", sa.String(), nullable=False),
        sa.Column("genus", sa.String(), nullable=False),
        sa.Column("family", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("taxon_id", name=op.f("pk_app_taxa")),
    )
    op.create_index("ix_app_taxa_taxon_id", "app_taxa", ["taxon_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_app_taxa_taxon_id", table_name="app_taxa")
    op.drop_table("app_taxa")
    # ### end Alembic commands ###
