"""added confidence to InatClassDataset

Revision ID: e9217b237685
Revises: e17629ed8f5d
Create Date: 2026-05-23 21:24:39.671280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9217b237685"
down_revision: Union[str, Sequence[str], None] = "e17629ed8f5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inat_classification_dataset", sa.Column("conf", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inat_classification_dataset", "conf")
    # ### end Alembic commands ###
